import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

const pretendardGov = localFont({
  src: '../assets/font/PretendardGOVVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard-gov'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendardGov.variable} antialiased`}>{children}</body>
    </html>
  );
}
